- Apache-Parquet-Loader/main.py
- README.md
This PR adds a simple script written in Python to make it easier to create a suitable model table for a folder of Apache Parquet files with equivalent schemas and then load the data they contain.
> Apache Parquet bulk loading script

- Evaluate-ModelarDB-Changes/main.py
This PR makes the evaluate [ModelarDB](https://github.com/ModelarData/ModelarDB-RS) changes script synchronize with `modelardbd` by pulling its current state and then sleeping for 10 seconds until `modelardbd` is in the correct state instead of just assuming it will take 10 seconds. This allows the script to evaluate changes that, e.g., increase the amount of time required for `modelardbd` to initialize and flush tables.
> Sync through state in evaluate change

- Evaluate-ModelarDB-Changes/main.py
This PR fixes an infinite loop in the evaluate changes script caused by a misunderstanding that [`Popen.poll()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.poll) returns `None` while the process is still running and not when it has terminated.
> Fix evaluate changes infinite loop due to None

- Git-Hooks/rust-pre-commit
- README.md
This PR adds a a pre-commit hook that ensures a Rust project contains no errors or warnings.
> Add Git pre-commit hook for Rust projects

- Git-Hooks/rust-pre-commit
Add [cargo machete](https://github.com/bnjbvr/cargo-machete) to the [pre-commit hook](https://github.com/ModelarData/Utilities/blob/dev/add-machete-to-hook/Git-Hooks/rust-pre-commit) to detect unused dependencies.
> Add cargo machete to pre-commit hook

- Git-Hooks/rust-pre-commit
This PR add --all-targets to cargo build, clippy, and test to ensure the commands are run for all targets in rust-pre-commit to match changes to [ModelarDB-RS GitHub Actions in PR #67](https://github.com/ModelarData/ModelarDB-RS/pull/67).
> Add --all-targets to cargo build, clippy, and test

- Git-Hooks/rust-pre-commit
This PR extends rust-pre-commit so it also runs the unit tests written in Python so the Python bindings are also tested before each commit is created.
> Add support for Python unittest to pre-commit

- Profile-ModelarDB-Compression/main.py
- README.md
This PR adds a script that computes how much storage each part of ModelarDB's compressed format uses at the logical database, table, and column level.
> Add ModelarDB compression profiling script

- Git-Hooks/rust-pre-commit
This PR make pre-commit not capture the output of `cargo test` so the seed added by ModelarData/ModelarDB-RS#109 can be read from the output and the automatically generated test data reproduced.
> Add --nocapture to cargo test to print the seed

- Evaluate-ModelarDB-Compression/main.py
This PR fixes a case where the actual error was represented as a ratio but then used as a percentage.
> Fix use of actual error in ratio as percentage

- Apache-Parquet-Loader/main.py
This PR makes the Apache Parquet Loader cast timestamps to milliseconds as it is the only [unit](https://arrow.apache.org/docs/python/generated/pyarrow.timestamp.html) supported.
> Cast timestamps in Apache Parquet Loader

- Profile-ModelarDB-Compression/main.py
This PR changes how the storage profiler configures the Apache Parquet file writer to match `modelardbd`.
> Make the storage profiler compress like modelardbd

- Evaluate-ModelarDB-Changes/main.py
`Evaluate-ModelarDB-Changes` forces `modelardbd` to compact the ingested data points by executing the query `SELECT * FROM evaluate_changes LIMIT 1`. As `Evaluate-ModelarDB-Changes` is designed to execute different query workloads from files to evaluate how changes to `modelardbd` impacts query performance, `SELECT * FROM evaluate_changes LIMIT 1` are written to a file and then executed. However, the file was not guaranteed to be flushed when it as passed to `modelardb` meaning compaction was done as part of the query workload instead of as a separate step.
> Ensure query forcing compaction is flushed

- Git-Hooks/rust-pre-commit
This PR removes the Python tools from `rust-pre-commit` due to ModelarData/ModelarDB-RS#155.
> Remove Python tools from rust-pre-commit hook

- Apache-Arrow-Flight-Manager-Tester/main.py
- Apache-Arrow-Flight-Server-Tester/main.py
- Apache-Parquet-Loader/main.py
- Evaluate-ModelarDB-Compression/main.py
- ModelarDB-Evaluator/src/client.rs
This PR makes all of the tools explicitly use a relative error bound in preparation for ModelarData/ModelarDB-RS#167. In addition to reviewing the chance, please also double check that all of the tools that creates `FIELD` columns with a non-zero error bound uses a relative error bound for consistency.
> Explicitly use relative error bounds

- Apache-Arrow-Flight-Tester/common.py
This PR removes the functionality to test the `UpdateRemoteObjectStore` action since this was removed from the Apache Arrow Flight servers of ModelarDB earlier.
> Removed function to update remote object store

- .gitignore
- Apache-Arrow-Flight-Tester/common.py
- Apache-Arrow-Flight-Tester/manager.py
- Apache-Arrow-Flight-Tester/server.py
- Apache-Parquet-Loader/main.py
- ModelarDB-Evaluator/src/client.rs
This PR adds a few new methods to the Apache Arrow Flight Tester that makes it easy to test `DropTable`, `TruncateTable`, and `NodeType` in both the server and manager.
> Added methods to drop, truncate, and get the node type to Apache Arrow Flight Tester

- Apache-Arrow-Flight-Tester/common.py
- Apache-Arrow-Flight-Tester/manager.py
- Apache-Arrow-Flight-Tester/server.py
This PR updates the Apache Arrow Flight Testers after creating, dropping, and truncating tables were moved to `do_get` from `do_action` in https://github.com/ModelarData/ModelarDB-RS/pull/266.
> Updated Apache Arrow Flights Testers to use do_get instead of do_action for creating, dropping, and truncating

- Apache-Parquet-Loader/main.py
This PR changes how `Apache-Parquet-Loader` creates tables from `do_action()`  to `do_get()`.
> Change create table from do_action to do_get

- ModelarDB-Storage-Insights/main.py
- README.md
This PR adds ModelarDB Storage Insights, a Python 3 script that computes how a model table stores time series. Currently, it computes which model types are used for each segment and how much space each column of the Apache Parquet files uses. Both are computed at the field level and table level. As the script cannot decompress the data points, it cannot provide any information at the data point level, such as how many data points are represented by each model type.
> Add ModelarDB Storage Insights

- Git-Hooks/rust-pre-commit
This PR adds `ast-grep` and `python unittest` to the `rust-pre-commit` Git hook. To reduce its runtime, the `--no-deps` flag has also been added to `cargo doc` as there is no need to generate the documentation for all dependencies when checking that a project's documentation can be generated without any issues.
> Add ast-grep and python unittest to pre-commit

- ModelarDB-Storage-Insights/main.py
This PR extends ModelarDB Storage Insights with a `Configuration` class to simplify determining how much storage is used for different configurations. It also replaces `FileResult` with `sqlite3` to simplify presenting the results using different aggregations.
> Add Config and SQLite3 to Storage Insights

- Apache-Arrow-Flight-Tester/common.py
- Apache-Arrow-Flight-Tester/manager.py
- Apache-Arrow-Flight-Tester/protobuf/protocol.proto
- Apache-Arrow-Flight-Tester/protobuf/protocol_pb2.py
- Apache-Arrow-Flight-Tester/protobuf/protocol_pb2.pyi
- Apache-Arrow-Flight-Tester/server.py
This PR updates the Apache Arrow Flight testers to match the changes made in https://github.com/ModelarData/ModelarDB-RS/pull/346. The PR adds new methods to make it possible to test the `CreateTable` action for both the server and manager and also removes the method that was used to test the `InitializeDatabase` endpoint. 
**Note that this PR should not be merged before https://github.com/ModelarData/ModelarDB-RS/pull/346 is merged.**
> Add methods to test CreateTable action

- Apache-Parquet-Loader/main.py
This PR changes `Apache-Parquet-Loader` so it only sends a `FlushMemory` `Action` at the end of loading instead of after each input file. This is done as flushing after each input file prevents `modelardbd` from batching compressed segments and thus it creates many small Apache Parquet files. In addition, it may hide issues with how `modelardbd` batches uncompressed data points and compressed segments and how it flushes compressed segments to disk.
> Make Apache Parquet Loader only flush at the end
